name: ds_algodealer
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - altair==6.0.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - ml-dtypes==0.2.0
      - narwhals==2.13.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - protobuf==4.25.8
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.1
      - tenacity==9.1.2
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.2.0
      - toml==0.10.2
      - tornado==6.5.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - watchdog==6.0.0
      - werkzeug==3.1.4
      - wrapt==1.14.2
prefix: /home/sam/anaconda3/envs/ds_algodealer
